### PR TITLE
See if travis-ci runs

### PR DESCRIPTION
**Pull request by tasleson**
Signed-off-by: Tony Asleson <tasleson@redhat.com>

### CODE REVIEW

**Comment by tasleson** [comment]
@cathay4t

Gris please take a peek at this, for some unknown reason I'm not able to `import dbus` on travis-ci.  I thought it was because the `sys.path` was missing `/usr/lib/python3/dist-packages`, but even after adding that I'm getting an import error.  Any ideas?  I think you ran into something like this when working with Joe on libStorageMgmt.

Before I added  `/usr/lib/python3/dist-packages`
```
missing dbus!
Dumping sys.path entries
library path= (['/home/travis/build/tasleson/a_posse_ad_esse', '/opt/python/3.6.0/lib/python36.zip', '/opt/python/3.6.0/lib/python3.6', '/opt/python/3.6.0/lib/python3.6/lib-dynload', '/opt/python/3.6.0/lib/python3.6/site-packages'])
```

After:
```
missing dbus!
Dumping sys.path entries
library path= (['/home/travis/build/tasleson/a_posse_ad_esse', '/usr/lib/python3/dist-packages', '/opt/python/3.6.0/lib/python36.zip', '/opt/python/3.6.0/lib/python3.6', '/opt/python/3.6.0/lib/python3.6/lib-dynload', '/opt/python/3.6.0/lib/python3.6/site-packages'])

Here is the directory
...
/usr/lib/python3/dist-packages/ufw-0.34_rc_0ubuntu2.egg-info
/usr/lib/python3/dist-packages/dbus
/usr/lib/python3/dist-packages/language_selector-0.1.egg-info
...
```

```python
#!/usr/bin/env python3

import sys
import os

try:
    import dbus
except:
    print('missing dbus!')

print('Dumping sys.path entries')
if __name__ == '__main__':
    print('library path= (%s)' % sys.path)

    for directory in sys.path:
        if os.path.isdir(directory):
            dir_listing = os.listdir(directory)
            for d in dir_listing:
                print('%s/%s' % (directory, d))
        else:
            print('sys.path entry %s not a directory' % directory)

    print('Hello travis-ci! %s' % str(sys.version_info))
```

**Comment by cathay4t** [comment]
My initial guess is travis is using quit old Ubuntu 12.04 which could be a touble maker.

Anyway, I will look into it.

**Comment by tasleson** [comment]
@cathay4t The image is `Ubuntu 14.04.5 LTS`

**Comment by cathay4t** [comment]
@tasleson Do you have the python traceback log for importing dbus? It might caused be possible some dependent package not installed.

**Comment by cathay4t** [comment]
@tasleson Never mind. I got the error message.

Please try change `.travis.yml`:

```
language: python
python:
  - "3.4"
```

**Pull request closed without merging**
